using TailorBD.API.Controllers;

namespace TailorBD.API.Services
{
    public interface IInvoiceBillingService
    {
        /// <summary>Create a single invoice for one institution.</summary>
        Task<int> CreateInvoiceForInstitutionAsync(
            int institutionId,
            string invoiceFor,
            DateTime issuDate,
            DateTime? endDate,
            double discount,
            IEnumerable<InvoiceLineRequest> lines,
            bool isAutoGenerated = false);

        /// <summary>One-click renew: uses Renew_Amount &amp; package interval.</summary>
        Task<int> RenewInstitutionAsync(int institutionId);

        /// <summary>Auto-generate monthly invoices for all institutions whose
        /// Expire_Date is today or in the past and no invoice exists for this month.</summary>
        Task<AutoGenerateResult> AutoGenerateForAllDueInstitutionsAsync();
    }

    public class AutoGenerateResult
    {
        public int Generated { get; set; }
        public int Skipped   { get; set; }
        public int Errors    { get; set; }
        public List<string> ErrorDetails { get; set; } = new();
    }
}
