using Dapper;
using TailorBD.API.Controllers;
using TailorBD.API.Data;

namespace TailorBD.API.Services
{
    public class InvoiceBillingService : IInvoiceBillingService
    {
        private readonly TailorBdContext _context;
        private readonly ILogger<InvoiceBillingService> _logger;

        public InvoiceBillingService(TailorBdContext context, ILogger<InvoiceBillingService> logger)
        {
            _context = context;
            _logger = logger;
        }

        // ── Create invoice for one institution ────────────────────────────────────
        public async Task<int> CreateInvoiceForInstitutionAsync(
            int institutionId,
            string invoiceFor,
            DateTime issuDate,
            DateTime? endDate,
            double discount,
            IEnumerable<InvoiceLineRequest> lines,
            bool isAutoGenerated = false)
        {
            using var con = _context.CreateConnection();
            con.Open();
            using var tx = con.BeginTransaction();
            try
            {
                // Get admin RegistrationID for this institution
                var regId = await con.ExecuteScalarAsync<int?>(
                    "SELECT TOP 1 RegistrationID FROM Registration WHERE InstitutionID=@id AND Category='Admin'",
                    new { id = institutionId }, tx);

                var totalAmount = lines.Sum(l => l.Amount);

                var invoiceId = await con.ExecuteScalarAsync<int>(
                    @"INSERT INTO Invoice
                        (InstitutionID, RegistrationID, IssuDate, EndDate,
                         Invoice_For, TotalAmount, PaidAmount, Discount,
                         PaymentStatus, CreateDate, IsAutoGenerated)
                      VALUES
                        (@InstitutionID, @RegistrationID, @IssuDate, @EndDate,
                         @InvoiceFor, @TotalAmount, 0, @Discount,
                         'Due', GETDATE(), @IsAutoGenerated);
                      SELECT CAST(SCOPE_IDENTITY() AS INT);",
                    new
                    {
                        InstitutionID  = institutionId,
                        RegistrationID = regId ?? 0,
                        IssuDate       = issuDate,
                        EndDate        = endDate,
                        InvoiceFor     = invoiceFor,
                        TotalAmount    = totalAmount,
                        Discount       = discount,
                        IsAutoGenerated = isAutoGenerated ? 1 : 0
                    }, tx);

                foreach (var line in lines)
                {
                    await con.ExecuteAsync(
                        @"INSERT INTO Invoice_Line
                            (InvoiceID, InstitutionID, RegistrationID, Details, Amount)
                          VALUES (@InvoiceID, @InstitutionID, @RegistrationID, @Details, @Amount)",
                        new
                        {
                            InvoiceID      = invoiceId,
                            InstitutionID  = institutionId,
                            RegistrationID = regId ?? 0,
                            line.Details,
                            line.Amount
                        }, tx);
                }

                tx.Commit();
                return invoiceId;
            }
            catch
            {
                tx.Rollback();
                throw;
            }
        }

        // ── One-click renew ───────────────────────────────────────────────────────
        public async Task<int> RenewInstitutionAsync(int institutionId)
        {
            using var con = _context.CreateConnection();

            var ins = await con.QuerySingleOrDefaultAsync(
                @"SELECT i.InstitutionName, i.Renew_Amount, i.PackageID,
                         i.Expire_Date, p.PackageName, p.Interval AS PackageInterval
                  FROM Institution i
                  LEFT JOIN Package p ON i.PackageID = p.PackageID
                  WHERE i.InstitutionID = @id",
                new { id = institutionId });

            if (ins == null)
                throw new InvalidOperationException($"Institution {institutionId} not found");

            double renewAmount = (double)(ins.Renew_Amount ?? 0);
            int intervalMonths = 1;
            string? intervalStr = ins.PackageInterval?.ToString();
            if (intervalStr != null && int.TryParse(intervalStr, out int parsedInterval))
                intervalMonths = parsedInterval;

            var issuDate = DateTime.Today;
            var endDate  = issuDate.AddMonths(intervalMonths);
            string packageName = ins.PackageName ?? "Monthly Package";

            var lines = new List<InvoiceLineRequest>
            {
                new() { Details = $"Renew — {packageName}", Amount = renewAmount }
            };

            var invoiceId = await CreateInvoiceForInstitutionAsync(
                institutionId,
                $"Monthly Renewal — {packageName}",
                issuDate, endDate,
                discount: 0, lines,
                isAutoGenerated: false);

            // Extend Expire_Date
            await con.ExecuteAsync(
                "UPDATE Institution SET Expire_Date = @ed WHERE InstitutionID = @id",
                new { ed = endDate, id = institutionId });

            return invoiceId;
        }

        // ── Auto-generate for all due institutions ─────────────────────────────────
        public async Task<AutoGenerateResult> AutoGenerateForAllDueInstitutionsAsync()
        {
            var result = new AutoGenerateResult();

            using var con = _context.CreateConnection();

            // Fetch institutions whose Expire_Date is today or past
            var institutions = await con.QueryAsync(
                @"SELECT i.InstitutionID, i.InstitutionName, i.Renew_Amount,
                         i.Expire_Date, i.PackageID,
                         p.PackageName, p.Interval AS PackageInterval
                  FROM Institution i
                  LEFT JOIN Package p ON i.PackageID = p.PackageID
                  WHERE i.Validation = 'Valid'
                    AND i.Expire_Date <= DATEADD(DAY, 1, GETDATE())");

            foreach (var ins in institutions)
            {
                try
                {
                    int insId = (int)ins.InstitutionID;
                    string month = DateTime.Today.ToString("yyyy-MM");

                    // Skip if an auto-generated invoice already exists this month
                    var alreadyExists = await con.ExecuteScalarAsync<int>(
                        @"SELECT COUNT(*) FROM Invoice
                          WHERE InstitutionID = @id
                            AND IsAutoGenerated = 1
                            AND FORMAT(CreateDate,'yyyy-MM') = @month",
                        new { id = insId, month });

                    if (alreadyExists > 0)
                    {
                        result.Skipped++;
                        continue;
                    }

                    double renewAmount = (double)(ins.Renew_Amount ?? 0);
                    int intervalMonths = 1;
                    string? intervalStr2 = ins.PackageInterval?.ToString();
                    if (intervalStr2 != null && int.TryParse(intervalStr2, out int pmVal))
                        intervalMonths = pmVal;

                    var issuDate = DateTime.Today;
                    var endDate  = issuDate.AddMonths(intervalMonths);
                    string pkgName = ins.PackageName ?? "Package";

                    await CreateInvoiceForInstitutionAsync(
                        insId,
                        $"Auto Monthly Renewal — {pkgName}",
                        issuDate, endDate,
                        discount: 0,
                        new[] { new InvoiceLineRequest { Details = $"Renew — {pkgName}", Amount = renewAmount } },
                        isAutoGenerated: true);

                    // Extend Expire_Date
                    await con.ExecuteAsync(
                        "UPDATE Institution SET Expire_Date = @ed WHERE InstitutionID = @id",
                        new { ed = endDate, id = insId });

                    result.Generated++;
                }
                catch (Exception ex)
                {
                    result.Errors++;
                    result.ErrorDetails.Add($"ID {ins.InstitutionID}: {ex.Message}");
                    _logger.LogError(ex, "Auto-generate failed for institution {Id}", (object)(int)ins.InstitutionID);
                }
            }

            // Write log
            try
            {
                await con.ExecuteAsync(
                    @"INSERT INTO InvoiceAutoLog (RunDate, Generated, Skipped, Errors, Details)
                      VALUES (GETDATE(), @Generated, @Skipped, @Errors, @Details)",
                    new
                    {
                        result.Generated, result.Skipped, result.Errors,
                        Details = string.Join("; ", result.ErrorDetails)
                    });
            }
            catch { /* log table may not exist yet; swallow */ }

            return result;
        }
    }
}
