using Dapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Caching.Memory;
using TailorBD.API.Data;
using TailorBD.API.Services;

namespace TailorBD.API.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class InvoiceController : ControllerBase
    {
        private readonly TailorBdContext _context;
        private readonly IInvoiceBillingService _billing;
        private readonly ILogger<InvoiceController> _logger;
        private readonly IMemoryCache _cache;

        // Schema flags — app চালু হওয়ার পর একবারই DB query করব
        private static readonly TimeSpan _schemaCacheDuration = TimeSpan.FromHours(24);

        public InvoiceController(
            TailorBdContext context,
            IInvoiceBillingService billing,
            ILogger<InvoiceController> logger,
            IMemoryCache cache)
        {
            _context = context;
            _billing = billing;
            _logger  = logger;
            _cache   = cache;
        }

        // ── Schema column existence — cached ──────────────────────────────────────
        private async Task<bool> ColumnExistsAsync(string table, string column)
        {
            var key = $"schema_col_{table}_{column}";
            if (_cache.TryGetValue(key, out bool exists)) return exists;

            using var con = _context.CreateConnection();
            exists = await con.ExecuteScalarAsync<int>(
                "SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME=@t AND COLUMN_NAME=@c",
                new { t = table, c = column }) > 0;

            _cache.Set(key, exists, _schemaCacheDuration);
            return exists;
        }

        // ── Cached SQL expressions for Invoice columns ────────────────────────────
        private async Task<(string totalAmountExpr, string paidAmountExpr, string isAutoGenExpr)> GetInvoiceExprsAsync()
        {
            bool hasTotalAmount = await ColumnExistsAsync("Invoice", "TotalAmount");
            bool hasPaidAmount  = await ColumnExistsAsync("Invoice", "PaidAmount");
            bool hasIsAutoGen   = await ColumnExistsAsync("Invoice", "IsAutoGenerated");

            var totalAmountExpr = hasTotalAmount
                ? "ISNULL(NULLIF(inv.TotalAmount,0), (SELECT ISNULL(SUM(Amount),0) FROM Invoice_Line WHERE InvoiceID=inv.InvoiceID))"
                : "(SELECT ISNULL(SUM(Amount),0) FROM Invoice_Line WHERE InvoiceID=inv.InvoiceID)";

            var paidAmountExpr = hasPaidAmount
                ? "inv.PaidAmount"
                : "ISNULL((SELECT SUM(Amount) FROM Invoice_Payment_Record WHERE InvoiceID=inv.InvoiceID),0)";

            var isAutoGenExpr = hasIsAutoGen ? "inv.IsAutoGenerated" : "0";

            return (totalAmountExpr, paidAmountExpr, isAutoGenExpr);
        }

        // ── GET /api/invoice/institutions ─────────────────────────────────────────
        /// <summary>Returns all institutions with their invoice/expiry summary.</summary>
        [HttpGet("institutions")]
        public async Task<ActionResult> GetInstitutions(
            [FromQuery] string? search = null,
            [FromQuery] string? validation = null,
            [FromQuery] string? expiry = null)
        {
            try
            {
                using var con = _context.CreateConnection();
                var sql = @"
                    SELECT
                        i.InstitutionID,
                        i.InstitutionName,
                        i.Phone,
                        i.Address,
                        i.Validation,
                        i.Expire_Date,
                        i.Renew_Amount,
                        i.PackageID,
                        p.PackageName,
                        p.Interval AS PackageInterval,
                        ISNULL(l.UserName,'') AS UserName,
                        ISNULL(SUM(
                            ISNULL(NULLIF(inv.TotalAmount,0), il_sum.LineTotal)
                            - ISNULL(inv.PaidAmount,0)
                            - ISNULL(inv.Discount,0)
                        ),0) AS TotalDue,
                        COUNT(inv.InvoiceID) AS TotalInvoices,
                        MAX(inv.CreateDate) AS LastInvoiceDate
                    FROM Institution i
                    LEFT JOIN Package  p   ON i.PackageID = p.PackageID
                    LEFT JOIN LIU      l   ON i.InstitutionID = l.InstitutionID AND l.Category='Admin'
                    LEFT JOIN Invoice  inv ON i.InstitutionID = inv.InstitutionID AND inv.PaymentStatus <> 'Paid'
                    LEFT JOIN (
                        SELECT InvoiceID, ISNULL(SUM(Amount),0) AS LineTotal
                        FROM Invoice_Line
                        GROUP BY InvoiceID
                    ) il_sum ON inv.InvoiceID = il_sum.InvoiceID
                    WHERE 1=1
                ";
                if (!string.IsNullOrWhiteSpace(validation))
                    sql += " AND i.Validation = @validation";
                if (!string.IsNullOrWhiteSpace(search))
                    sql += " AND (i.InstitutionName LIKE @search OR i.Phone LIKE @search OR l.UserName LIKE @search)";
                if (expiry == "expired")
                    sql += " AND i.Expire_Date < GETDATE()";
                else if (expiry == "expiring")
                    sql += " AND i.Expire_Date BETWEEN GETDATE() AND DATEADD(DAY,15,GETDATE())";

                sql += @" GROUP BY i.InstitutionID, i.InstitutionName, i.Phone,
                                   i.Address, i.Validation, i.Expire_Date, i.Renew_Amount,
                                   i.PackageID, p.PackageName, p.Interval, l.UserName
                          ORDER BY i.InstitutionID DESC";

                var parameters = new DynamicParameters();
                if (!string.IsNullOrWhiteSpace(validation))
                    parameters.Add("validation", validation);
                if (!string.IsNullOrWhiteSpace(search))
                    parameters.Add("search", "%" + search + "%");

                var rows = await con.QueryAsync(sql, parameters);

                // Project to camelCase so JS field names match exactly
                var data = rows.Select(r => new
                {
                    institutionId = (int)r.InstitutionID,
                    institutionName = (string)(r.InstitutionName ?? ""),
                    phone = (string)(r.Phone ?? ""),
                    address = (string)(r.Address ?? ""),
                    validation = (string)(r.Validation ?? ""),
                    expire_Date = r.Expire_Date == null ? (DateTime?)null : (DateTime)r.Expire_Date,
                    renewAmount = r.Renew_Amount == null ? 0.0 : Convert.ToDouble(r.Renew_Amount),
                    packageId = r.PackageID == null ? 0 : (int)r.PackageID,
                    packageName = (string)(r.PackageName ?? ""),
                    packageInterval = r.PackageInterval == null ? (int?)null : (int)r.PackageInterval,
                    userName = (string)(r.UserName ?? ""),
                    totalDue = Convert.ToDouble(r.TotalDue ?? 0),
                    totalInvoices = (int)(r.TotalInvoices ?? 0),
                    lastInvoiceDate = r.LastInvoiceDate == null ? (DateTime?)null : (DateTime)r.LastInvoiceDate,
                }).ToList();

                return Ok(new { success = true, data });
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error fetching institutions for invoice");
                return StatusCode(500, new { success = false, message = ex.Message });
            }
        }

        // ── GET /api/invoice/list ──────────────────────────────────────────────────
        /// <summary>Returns invoice list, optionally filtered by institution.</summary>
        [HttpGet("list")]
        public async Task<ActionResult> GetInvoices(
            [FromQuery] int? institutionId = null,
            [FromQuery] string? status = null,
            [FromQuery] int page = 1,
            [FromQuery] int pageSize = 20)
        {
            try
            {
                var (totalAmountExpr, paidAmountExpr, isAutoGenExpr) = await GetInvoiceExprsAsync();

                using var con = _context.CreateConnection();

                var sql = $@"
                    SELECT
                        inv.InvoiceID,
                        inv.InstitutionID,
                        i.InstitutionName,
                        inv.IssuDate,
                        inv.EndDate,
                        inv.Invoice_For,
                        {totalAmountExpr} AS TotalAmount,
                        {paidAmountExpr}  AS PaidAmount,
                        ISNULL(inv.Discount,0) AS Discount,
                        inv.PaymentStatus,
                        inv.CreateDate,
                        {isAutoGenExpr}   AS IsAutoGenerated,
                        ISNULL(l.UserName,'') AS UserName
                    FROM Invoice inv
                    JOIN Institution i ON inv.InstitutionID = i.InstitutionID
                    LEFT JOIN LIU l ON inv.InstitutionID = l.InstitutionID AND l.Category='Admin'
                    WHERE 1=1";

                if (institutionId.HasValue) sql += " AND inv.InstitutionID = @institutionId";
                if (!string.IsNullOrWhiteSpace(status)) sql += " AND inv.PaymentStatus = @status";
                sql += " ORDER BY inv.CreateDate DESC OFFSET @offset ROWS FETCH NEXT @pageSize ROWS ONLY";

                var rows = await con.QueryAsync(sql, new
                {
                    institutionId,
                    status,
                    offset   = (page - 1) * pageSize,
                    pageSize
                });

                var countSql = "SELECT COUNT(*) FROM Invoice inv WHERE 1=1" +
                    (institutionId.HasValue ? " AND inv.InstitutionID=@institutionId" : "") +
                    (!string.IsNullOrWhiteSpace(status) ? " AND inv.PaymentStatus=@status" : "");
                var total = await con.ExecuteScalarAsync<int>(countSql, new { institutionId, status });

                var data = rows.Select(r => new
                {
                    invoiceID       = (int)r.InvoiceID,
                    institutionID   = (int)r.InstitutionID,
                    institutionName = (string)(r.InstitutionName ?? ""),
                    issuDate        = r.IssuDate  == null ? (DateTime?)null : (DateTime)r.IssuDate,
                    endDate         = r.EndDate   == null ? (DateTime?)null : (DateTime)r.EndDate,
                    invoice_For     = (string)(r.Invoice_For ?? ""),
                    totalAmount     = r.TotalAmount == null ? 0.0 : Convert.ToDouble(r.TotalAmount),
                    paidAmount      = r.PaidAmount  == null ? 0.0 : Convert.ToDouble(r.PaidAmount),
                    discount        = r.Discount    == null ? 0.0 : Convert.ToDouble(r.Discount),
                    paymentStatus   = (string)(r.PaymentStatus ?? "Due"),
                    createDate      = r.CreateDate == null ? (DateTime?)null : (DateTime)r.CreateDate,
                    isAutoGenerated = r.IsAutoGenerated != null && Convert.ToInt32(r.IsAutoGenerated) == 1,
                    userName        = (string)(r.UserName ?? ""),
                }).ToList();

                return Ok(new { success = true, data, total, page, pageSize });
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error fetching invoices");
                return StatusCode(500, new { success = false, message = ex.Message });
            }
        }

        // ── GET /api/invoice/{id}/lines ────────────────────────────────────────────
        [HttpGet("{id}/lines")]
        public async Task<ActionResult> GetInvoiceLines(int id)
        {
            try
            {
                using var con = _context.CreateConnection();
                var lines = await con.QueryAsync(
                    "SELECT * FROM Invoice_Line WHERE InvoiceID=@id ORDER BY Invoice_LineID",
                    new { id });
                return Ok(new { success = true, data = lines });
            }
            catch (Exception ex)
            {
                return StatusCode(500, new { success = false, message = ex.Message });
            }
        }

        // ── GET /api/invoice/{id}/payments ─────────────────────────────────────────
        [HttpGet("{id}/payments")]
        public async Task<ActionResult> GetInvoicePayments(int id)
        {
            try
            {
                using var con = _context.CreateConnection();
                var payments = await con.QueryAsync(
                    @"SELECT InvoicePaymentRecordID, InvoiceID, Amount, PaidDate,
                             ISNULL(Collected_By,'') AS Collected_By,
                             ISNULL(Payment_Method,'') AS Payment_Method
                      FROM Invoice_Payment_Record
                      WHERE InvoiceID=@id
                      ORDER BY PaidDate DESC",
                    new { id });

                var data = payments.Select(r => new
                {
                    invoicePaymentRecordID = (int)r.InvoicePaymentRecordID,
                    invoiceID      = (int)r.InvoiceID,
                    amount         = r.Amount == null ? 0.0 : Convert.ToDouble(r.Amount),
                    paidDate       = r.PaidDate == null ? (DateTime?)null : (DateTime)r.PaidDate,
                    collected_By   = (string)(r.Collected_By   ?? ""),
                    payment_Method = (string)(r.Payment_Method ?? "")
                }).ToList();

                return Ok(new { success = true, data });
            }
            catch (Exception ex)
            {
                return StatusCode(500, new { success = false, message = ex.Message });
            }
        }

        // ── GET /api/invoice/{id}/detail ───────────────────────────────────────────
        /// <summary>Returns both invoice lines and payment records for a single invoice.</summary>
        [HttpGet("{id}/detail")]
        public async Task<ActionResult> GetInvoiceDetail(int id)
        {
            try
            {
                using var con = _context.CreateConnection();

                var lineData = new List<object>();
                var paymentData = new List<object>();

                try
                {
                    var lines = await con.QueryAsync(
                        "SELECT Details, Amount FROM Invoice_Line WHERE InvoiceID=@id",
                        new { id });
                    lineData = lines.Select(r => new
                    {
                        details = r.Details == null ? "" : (string)r.Details,
                        amount = r.Amount == null ? 0.0 : Convert.ToDouble(r.Amount)
                    }).Cast<object>().ToList();
                }
                catch (Exception ex)
                {
                    _logger.LogWarning(ex, "Could not load invoice lines for InvoiceID={id}", id);
                }

                try
                {
                    var payments = await con.QueryAsync(
                        @"SELECT Amount, PaidDate,
                                 ISNULL(Collected_By,'') AS Collected_By,
                                 ISNULL(Payment_Method,'') AS Payment_Method
                          FROM Invoice_Payment_Record
                          WHERE InvoiceID=@id
                          ORDER BY PaidDate DESC",
                        new { id });
                    paymentData = payments.Select(r => new
                    {
                        amount = r.Amount == null ? 0.0 : Convert.ToDouble(r.Amount),
                        paidDate = r.PaidDate == null ? (DateTime?)null : (DateTime)r.PaidDate,
                        collected_By = (string)(r.Collected_By ?? ""),
                        payment_Method = (string)(r.Payment_Method ?? "")
                    }).Cast<object>().ToList();
                }
                catch (Exception ex)
                {
                    _logger.LogWarning(ex, "Could not load payment records for InvoiceID={id}", id);
                }

                return Ok(new { success = true, lines = lineData, payments = paymentData });
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error in GetInvoiceDetail for InvoiceID={id}", id);
                return StatusCode(500, new { success = false, message = ex.Message });
            }
        }

        // ── POST /api/invoice/create ───────────────────────────────────────────────
        /// <summary>Manually create invoices for selected institutions.</summary>
        [HttpPost("create")]
        public async Task<ActionResult> CreateInvoices([FromBody] CreateInvoiceRequest req)
        {
            if (req.InstitutionIds == null || !req.InstitutionIds.Any())
                return BadRequest(new { success = false, message = "No institutions selected" });
            if (!req.Lines.Any())
                return BadRequest(new { success = false, message = "At least one invoice line required" });

            try
            {
                var created = 0;
                var errors = new List<string>();

                foreach (var insId in req.InstitutionIds)
                {
                    try
                    {
                        await _billing.CreateInvoiceForInstitutionAsync(
                            insId,
                            req.InvoiceFor,
                            req.IssuDate ?? DateTime.Today,
                            req.EndDate,
                            req.Discount,
                            req.Lines,
                            isAutoGenerated: false);
                        created++;
                    }
                    catch (Exception ex)
                    {
                        errors.Add($"InstitutionID {insId}: {ex.Message}");
                    }
                }

                return Ok(new
                {
                    success = true,
                    message = $"{created} invoice(s) created successfully",
                    created,
                    errors
                });
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error creating invoices");
                return StatusCode(500, new { success = false, message = ex.Message });
            }
        }

        // ── POST /api/invoice/auto-generate ───────────────────────────────────────
        /// <summary>Manually trigger auto-bill generation for all due institutions.</summary>
        [HttpPost("auto-generate")]
        public async Task<ActionResult> TriggerAutoGenerate()
        {
            try
            {
                var result = await _billing.AutoGenerateForAllDueInstitutionsAsync();
                return Ok(new
                {
                    success = true,
                    message = $"Auto-generate complete: {result.Generated} created, {result.Skipped} skipped, {result.Errors} errors",
                    result
                });
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error in auto-generate");
                return StatusCode(500, new { success = false, message = ex.Message });
            }
        }

        // ── POST /api/invoice/renew/{institutionId} ────────────────────────────────
        /// <summary>One-click renew for a single institution (uses Renew_Amount from Institution).</summary>
        [HttpPost("renew/{institutionId}")]
        public async Task<ActionResult> RenewInstitution(int institutionId)
        {
            try
            {
                var invoiceId = await _billing.RenewInstitutionAsync(institutionId);
                return Ok(new { success = true, message = "Renewal invoice created", invoiceId });
            }
            catch (Exception ex)
            {
                return StatusCode(500, new { success = false, message = ex.Message });
            }
        }

        // ── PUT /api/invoice/{id}/payment ──────────────────────────────────────────
        /// <summary> Update payment status / paid amount.</summary>
        [HttpPut("{id}/payment")]
        public async Task<ActionResult> UpdatePayment(int id, [FromBody] UpdatePaymentRequest req)
        {
            try
            {
                using var con = _context.CreateConnection();
                con.Open();
                using var tx = con.BeginTransaction();
                try
                {
                    // ── 1. Load current invoice state ─────────────────────────
                    var invRow = await con.QueryFirstOrDefaultAsync(
                        @"SELECT inv.PaidAmount,
                                 ISNULL(inv.Discount, 0) AS Discount,
                                 inv.InstitutionID, inv.RegistrationID,
                                 ISNULL(NULLIF(inv.TotalAmount, 0),
                                     (SELECT ISNULL(SUM(Amount),0) FROM Invoice_Line WHERE InvoiceID = inv.InvoiceID)
                                 ) AS TotalAmount
                          FROM Invoice inv WHERE inv.InvoiceID = @id",
                        new { id }, tx);

                    if (invRow == null)
                        return NotFound(new { success = false, message = "Invoice not found" });

                    double prevPaid      = invRow.PaidAmount  == null ? 0.0 : Convert.ToDouble(invRow.PaidAmount);
                    double prevDiscount  = invRow.Discount    == null ? 0.0 : Convert.ToDouble(invRow.Discount);
                    double totalAmount   = invRow.TotalAmount == null ? 0.0 : Convert.ToDouble(invRow.TotalAmount);
                    int    institutionId = (int)invRow.InstitutionID;
                    int    registrationId = invRow.RegistrationID == null ? 0 : (int)invRow.RegistrationID;

                    double addedAmount   = req.AddedAmount;
                    double addedDiscount = req.Discount;
                    double newDiscount   = prevDiscount + addedDiscount;
                    // Cap PaidAmount so it never exceeds TotalAmount - Discount (trigger guard)
                    double newPaid       = Math.Min(prevPaid + addedAmount, Math.Max(0, totalAmount - newDiscount));
                    double effectivePaid = newPaid + newDiscount;    // paid + discount মিলিয়ে

                    string paymentStatus = effectivePaid >= totalAmount ? "Paid"
                                        : newPaid > 0 || newDiscount > 0 ? "Partial"
                                        : "Due";

                    // ── 2. Update Invoice table ───────────────────────────────
                    await con.ExecuteAsync(
                        @"UPDATE Invoice
                          SET PaidAmount    = @NewPaid,
                              Discount      = @NewDiscount,
                              PaymentStatus = @PaymentStatus
                          WHERE InvoiceID   = @id",
                        new { NewPaid = newPaid, NewDiscount = newDiscount, PaymentStatus = paymentStatus, id }, tx);

                    // ── 3. Insert payment record only if cash was added ───────
                    if (addedAmount > 0)
                    {
                        var collectedBy   = string.IsNullOrWhiteSpace(req.CollectedBy)
                                            ? sessionStorage_GetUsername(Request) : req.CollectedBy;
                        var paymentMethod = string.IsNullOrWhiteSpace(req.PaymentMethod)
                                            ? "Cash" : req.PaymentMethod;

                        await con.ExecuteAsync(
                            @"INSERT INTO Invoice_Payment_Record
                                (InvoiceID, InstitutionID, RegistrationID, Amount, PaidDate, Collected_By, Payment_Method)
                              VALUES
                                (@InvoiceID, @InstitutionID, @RegistrationID, @Amount, GETDATE(), @CollectedBy, @PaymentMethod)",
                            new
                            {
                                InvoiceID      = id,
                                InstitutionID  = institutionId,
                                RegistrationID = registrationId,
                                Amount         = addedAmount,
                                CollectedBy    = collectedBy,
                                PaymentMethod  = paymentMethod
                            }, tx);
                    }

                    tx.Commit();
                    return Ok(new { success = true, message = "Payment updated", paymentStatus });
                }
                catch
                {
                    tx.Rollback();
                    throw;
                }
            }
            catch (Exception ex)
            {
                return StatusCode(500, new { success = false, message = ex.Message });
            }
        }

        // ── POST /api/invoice/bulk-payment ────────────────────────────────────────
        /// <summary>Pay multiple invoices in a single transaction — avoids deadlock.</summary>
        [HttpPost("bulk-payment")]
        public async Task<ActionResult> BulkPayment([FromBody] BulkPaymentRequest req)
        {
            if (req.Payments == null || !req.Payments.Any())
                return BadRequest(new { success = false, message = "No payments provided" });

            var collectedBy   = string.IsNullOrWhiteSpace(req.CollectedBy)
                                ? sessionStorage_GetUsername(Request) : req.CollectedBy;
            var paymentMethod = string.IsNullOrWhiteSpace(req.PaymentMethod) ? "Cash" : req.PaymentMethod;

            try
            {
                using var con = _context.CreateConnection();
                con.Open();
                using var tx = con.BeginTransaction(System.Data.IsolationLevel.ReadCommitted);
                try
                {
                    int processed = 0;
                    foreach (var p in req.Payments)
                    {
                        // ── Load invoice (with UPDLOCK to prevent deadlock) ────
                        var invRow = await con.QueryFirstOrDefaultAsync(
                            @"SELECT inv.PaidAmount,
                                     ISNULL(inv.Discount, 0) AS Discount,
                                     inv.InstitutionID, inv.RegistrationID,
                                     ISNULL(NULLIF(inv.TotalAmount, 0),
                                         (SELECT ISNULL(SUM(Amount),0) FROM Invoice_Line WHERE InvoiceID = inv.InvoiceID)
                                     ) AS TotalAmount
                              FROM Invoice inv WITH (UPDLOCK, ROWLOCK)
                              WHERE inv.InvoiceID = @id",
                            new { id = p.InvoiceId }, tx);

                        if (invRow == null) continue;

                        double prevPaid      = invRow.PaidAmount  == null ? 0.0 : Convert.ToDouble(invRow.PaidAmount);
                        double prevDiscount  = invRow.Discount    == null ? 0.0 : Convert.ToDouble(invRow.Discount);
                        double totalAmount   = invRow.TotalAmount == null ? 0.0 : Convert.ToDouble(invRow.TotalAmount);
                        int    institutionId  = (int)invRow.InstitutionID;
                        int    registrationId = invRow.RegistrationID == null ? 0 : (int)invRow.RegistrationID;

                        double addedDiscount = p.Discount;
                        double newDiscount   = prevDiscount + addedDiscount;
                        double newPaid       = Math.Min(prevPaid + p.AddedAmount, Math.Max(0, totalAmount - newDiscount));
                        double effectivePaid = newPaid + newDiscount;

                        string status = effectivePaid >= totalAmount ? "Paid"
                                      : newPaid > 0 || newDiscount > 0 ? "Partial"
                                      : "Due";

                        await con.ExecuteAsync(
                            @"UPDATE Invoice
                              SET PaidAmount    = @NewPaid,
                                  Discount      = @NewDiscount,
                                  PaymentStatus = @Status
                              WHERE InvoiceID   = @id",
                            new { NewPaid = newPaid, NewDiscount = newDiscount, Status = status, id = p.InvoiceId }, tx);

                        if (p.AddedAmount > 0)
                        {
                            await con.ExecuteAsync(
                                @"INSERT INTO Invoice_Payment_Record
                                    (InvoiceID, InstitutionID, RegistrationID, Amount, PaidDate, Collected_By, Payment_Method)
                                  VALUES
                                    (@InvoiceID, @InstitutionID, @RegistrationID, @Amount, GETDATE(), @CollectedBy, @PaymentMethod)",
                                new
                                {
                                    InvoiceID      = p.InvoiceId,
                                    InstitutionID  = institutionId,
                                    RegistrationID = registrationId,
                                    Amount         = p.AddedAmount,
                                    CollectedBy    = collectedBy,
                                    PaymentMethod  = paymentMethod
                                }, tx);
                        }

                        processed++;
                    }

                    tx.Commit();
                    return Ok(new { success = true, message = $"{processed} টি Invoice পেমেন্ট সফল", processed });
                }
                catch
                {
                    tx.Rollback();
                    throw;
                }
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error in BulkPayment");
                return StatusCode(500, new { success = false, message = ex.Message });
            }
        }

        // ── helper: username from Authorization header ─────────────────────────────
        private static string sessionStorage_GetUsername(HttpRequest request)
        {
            var auth = request.Headers["X-Username"].ToString();
            return string.IsNullOrWhiteSpace(auth) ? "Authority" : auth;
        }

        // ── GET /api/invoice/payment-summary ──────────────────────────────────────
        /// <summary>Returns paid payment records grouped by date+method+collector for an institution.</summary>
        [HttpGet("payment-summary")]
        public async Task<ActionResult> GetPaymentSummary([FromQuery] int? institutionId = null)
        {
            if (institutionId == null || institutionId <= 0)
                return BadRequest(new { success = false, message = "institutionId is required" });

            try
            {
                var (totalAmountExpr, _, _) = await GetInvoiceExprsAsync();

                using var con = _context.CreateConnection();

                // ── Per-invoice details (Paid or Partial) ─────────────────────
                var invRows = await con.QueryAsync($@"
                    SELECT
                        inv.InvoiceID,
                        inv.Invoice_For,
                        inv.IssuDate,
                        inv.EndDate,
                        CAST(ISNULL(inv.Discount,   0) AS FLOAT) AS Discount,
                        CAST(ISNULL(inv.PaidAmount, 0) AS FLOAT) AS PaidAmount,
                        CAST(({totalAmountExpr})       AS FLOAT) AS InvoiceTotalAmount
                    FROM Invoice inv
                    WHERE inv.InstitutionID = @institutionId
                      AND inv.PaymentStatus IN ('Paid','Partial')",
                    new { institutionId });

                var invDict = new Dictionary<int, object>();
                foreach (var r in invRows)
                {
                    int key = Convert.ToInt32(r.InvoiceID);
                    if (!invDict.ContainsKey(key))
                        invDict[key] = new
                        {
                            invoiceID          = key,
                            invoice_For        = (string)(r.Invoice_For ?? ""),
                            issuDate           = r.IssuDate  == null ? (DateTime?)null : (DateTime)r.IssuDate,
                            endDate            = r.EndDate   == null ? (DateTime?)null : (DateTime)r.EndDate,
                            discount           = r.Discount           == null ? 0.0 : Convert.ToDouble(r.Discount),
                            paidAmount         = r.PaidAmount         == null ? 0.0 : Convert.ToDouble(r.PaidAmount),
                            invoiceTotalAmount = r.InvoiceTotalAmount == null ? 0.0 : Convert.ToDouble(r.InvoiceTotalAmount)
                        };
                }

                // ── Payment records ───────────────────────────────────────────
                var payRows = await con.QueryAsync(@"
                    SELECT
                        CAST(pr.PaidDate AS DATE)                AS PaidDate,
                        ISNULL(pr.Payment_Method, 'Cash')        AS Payment_Method,
                        ISNULL(pr.Collected_By, '')              AS Collected_By,
                        CAST(ISNULL(pr.Amount, 0) AS FLOAT)     AS Amount,
                        pr.InvoiceID
                    FROM Invoice_Payment_Record pr
                    WHERE pr.InstitutionID = @institutionId
                    ORDER BY CAST(pr.PaidDate AS DATE) DESC",
                    new { institutionId });

                // ── Group by date + method + collector ────────────────────────
                var grouped = payRows
                    .GroupBy(r => new
                    {
                        PaidDate    = r.PaidDate == null
                                        ? DateTime.Today.Date
                                        : ((DateTime)r.PaidDate).Date,
                        Method      = (string)(r.Payment_Method ?? "Cash"),
                        CollectedBy = (string)(r.Collected_By   ?? "")
                    })
                    .OrderByDescending(g => g.Key.PaidDate)
                    .Select(g =>
                    {
                        var invoiceIds = g
                            .Select(r => Convert.ToInt32(r.InvoiceID))
                            .Distinct()
                            .ToList();

                        var invoiceDetails = invoiceIds
                            .Where(id => invDict.ContainsKey(id))
                            .Select(id => invDict[id])
                            .ToList();

                        double total = 0;
                        foreach (var r in g)
                            total += (double)(r.Amount ?? 0.0);

                        return new
                        {
                            paidDate       = (DateTime?)g.Key.PaidDate,
                            payment_Method = g.Key.Method,
                            collected_By   = g.Key.CollectedBy,
                            totalAmount    = total,
                            invoices       = invoiceDetails
                        };
                    })
                    .ToList();

                return Ok(new { success = true, data = grouped });
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error in GetPaymentSummary for institution {id}", institutionId);
                return StatusCode(500, new { success = false, message = ex.Message });
            }
        }

        // ── GET /api/invoice/due-status/{institutionId} ───────────────────────────
        [HttpGet("due-status/{institutionId}")]
        public async Task<ActionResult> GetDueStatus(int institutionId)
        {
            try
            {
                var (totalAmountExpr, paidAmountExpr, _) = await GetInvoiceExprsAsync();

                using var con = _context.CreateConnection();

                // ── সার্ভিস চার্জ due invoices ──
                var serviceRows = await con.QueryAsync($@"
                    SELECT
                        inv.InvoiceID,
                        CAST(({totalAmountExpr}) - ({paidAmountExpr}) AS FLOAT) AS DueAmount,
                        inv.CreateDate,
                        ISNULL(inv.Invoice_For,'Service') AS Invoice_For
                    FROM Invoice inv
                    WHERE inv.InstitutionID = @InstitutionID
                      AND inv.PaymentStatus <> 'Paid'
                      AND (inv.Invoice_For NOT LIKE '%SMS%' OR inv.Invoice_For IS NULL)
                    ORDER BY inv.CreateDate ASC",
                    new { InstitutionID = institutionId });

                var serviceList = serviceRows.ToList();
                double totalDueAmount = serviceList.Sum(r => (double)(r.DueAmount ?? 0.0));
                int dueCount = serviceList.Count;

                bool showPopup = false, accessBlocked = false, closeable = true;
                int graceDaysRemaining = 0;

                if (dueCount > 0)
                {
                    showPopup = true;
                    var oldestDate = serviceList.Min(r => r.CreateDate == null ? DateTime.Today : (DateTime)r.CreateDate);
                    var daysSince = (DateTime.Today - oldestDate.Date).Days;
                    graceDaysRemaining = Math.Max(0, 7 - daysSince);
                    accessBlocked = daysSince > 7;
                    closeable     = !accessBlocked;
                }

                // ── SMS রিচার্জ due invoices ──
                var smsRows = await con.QueryAsync($@"
                    SELECT
                        inv.InvoiceID,
                        CAST(({totalAmountExpr}) - ({paidAmountExpr}) AS FLOAT) AS DueAmount,
                        inv.CreateDate
                    FROM Invoice inv
                    WHERE inv.InstitutionID = @InstitutionID
                      AND inv.PaymentStatus <> 'Paid'
                      AND inv.Invoice_For LIKE '%SMS%'
                    ORDER BY inv.CreateDate ASC",
                    new { InstitutionID = institutionId });

                var smsList = smsRows.ToList();
                double smsTotalDueAmount = smsList.Sum(r => (double)(r.DueAmount ?? 0.0));
                int smsDueCount = smsList.Count;

                bool smsShowPopup = false, smsAccessBlocked = false, smsCloseable = true;
                if (smsDueCount > 0)
                {
                    smsShowPopup = true;
                    var smsOldest    = smsList.Min(r => r.CreateDate == null ? DateTime.Today : (DateTime)r.CreateDate);
                    var smsDaysSince = (DateTime.Today - smsOldest.Date).Days;
                    smsAccessBlocked = smsDaysSince > 7;
                    smsCloseable     = !smsAccessBlocked;
                }

                return Ok(new
                {
                    success = true,
                    data = new
                    {
                        showPopup, accessBlocked, closeable, graceDaysRemaining,
                        dueCount, totalDueAmount,
                        smsShowPopup, smsAccessBlocked, smsCloseable,
                        smsDueCount, smsTotalDueAmount
                    }
                });
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error in GetDueStatus for institution {id}", institutionId);
                return StatusCode(500, new { success = false, message = ex.Message });
            }
        }

        // ── GET /api/invoice/authority/collected-payments ─────────────────────────
        [HttpGet("authority/collected-payments")]
        public async Task<ActionResult> GetAuthorityCollectedPayments(
            [FromQuery] string? fromDate = null,
            [FromQuery] string? toDate   = null)
        {
            try
            {
                using var con = _context.CreateConnection();

                var from = string.IsNullOrWhiteSpace(fromDate)
                    ? new DateTime(DateTime.Today.Year, DateTime.Today.Month, 1)
                    : DateTime.Parse(fromDate);
                var to = string.IsNullOrWhiteSpace(toDate)
                    ? DateTime.Today
                    : DateTime.Parse(toDate);

                // 1. Payment records in the requested date range
                var payRows = await con.QueryAsync(@"
                    SELECT
                        pr.InvoicePaymentRecordID,
                        pr.InvoiceID,
                        pr.InstitutionID,
                        i.InstitutionName,
                        CAST(pr.PaidDate AS DATE)            AS PaidDate,
                        CAST(ISNULL(pr.Amount,0) AS FLOAT)  AS PaidAmount,
                        ISNULL(pr.Collected_By,'')          AS Collected_By,
                        ISNULL(pr.Payment_Method,'')        AS Payment_Method,
                        ISNULL(inv.Invoice_For,'')          AS Invoice_For,
                        CAST(ISNULL(inv.Discount,0) AS FLOAT) AS Discount
                    FROM Invoice_Payment_Record pr
                    JOIN Invoice     inv ON pr.InvoiceID     = inv.InvoiceID
                    JOIN Institution i   ON pr.InstitutionID = i.InstitutionID
                    WHERE CAST(pr.PaidDate AS DATE) BETWEEN @from AND @to
                    ORDER BY pr.PaidDate DESC, pr.InvoicePaymentRecordID DESC",
                    new { from, to });

                // 2. Current-month summary (always current month, ignores date filter)
                var monthStart = new DateTime(DateTime.Today.Year, DateTime.Today.Month, 1);
                var monthEnd   = DateTime.Today;

                var summaryRow = await con.QueryFirstOrDefaultAsync(@"
                    SELECT
                        CAST(ISNULL(SUM(pr.Amount),0) AS FLOAT) AS MonthCollected,
                        COUNT(DISTINCT pr.InstitutionID)         AS InstitutionsPaid,
                        COUNT(pr.InvoicePaymentRecordID)         AS PaymentCount
                    FROM Invoice_Payment_Record pr
                    WHERE CAST(pr.PaidDate AS DATE) BETWEEN @monthStart AND @monthEnd",
                    new { monthStart, monthEnd });

                double monthCollected   = summaryRow?.MonthCollected   == null ? 0.0 : Convert.ToDouble(summaryRow.MonthCollected);
                int    institutionsPaid = summaryRow?.InstitutionsPaid  == null ? 0   : Convert.ToInt32(summaryRow.InstitutionsPaid);
                int    paymentCount     = summaryRow?.PaymentCount      == null ? 0   : Convert.ToInt32(summaryRow.PaymentCount);

                // 3. Due list (all institutions that still owe money)
                var dueRows = await con.QueryAsync(@"
                    SELECT
                        i.InstitutionID,
                        i.InstitutionName,
                        ISNULL(l.UserName,'')  AS UserName,
                        i.Phone,
                        i.Validation,
                        CAST(ISNULL(SUM(
                            ISNULL(NULLIF(inv.TotalAmount,0), il_s.LineTotal)
                            - ISNULL(inv.PaidAmount,0)
                            - ISNULL(inv.Discount,0)
                        ),0) AS FLOAT)          AS TotalDue,
                        COUNT(inv.InvoiceID)   AS DueInvoiceCount
                    FROM Institution i
                    LEFT JOIN LIU l ON i.InstitutionID = l.InstitutionID AND l.Category = 'Admin'
                    LEFT JOIN Invoice inv ON i.InstitutionID = inv.InstitutionID AND inv.PaymentStatus <> 'Paid'
                    LEFT JOIN (
                        SELECT InvoiceID, ISNULL(SUM(Amount),0) AS LineTotal
                        FROM Invoice_Line GROUP BY InvoiceID
                    ) il_s ON inv.InvoiceID = il_s.InvoiceID
                    GROUP BY i.InstitutionID, i.InstitutionName, l.UserName, i.Phone, i.Validation
                    HAVING SUM(ISNULL(NULLIF(inv.TotalAmount,0), il_s.LineTotal) - ISNULL(inv.PaidAmount,0)) > 0
                    ORDER BY TotalDue DESC",
                    null);

                var payments = payRows.Select(r => new {
                    invoicePaymentRecordID = (int)r.InvoicePaymentRecordID,
                    invoiceID       = (int)r.InvoiceID,
                    institutionID   = (int)r.InstitutionID,
                    institutionName = (string)(r.InstitutionName ?? ""),
                    paidDate        = r.PaidDate == null ? (DateTime?)null : (DateTime)r.PaidDate,
                    paidAmount      = (double)r.PaidAmount,
                    collected_By    = (string)(r.Collected_By   ?? ""),
                    payment_Method  = (string)(r.Payment_Method ?? ""),
                    invoice_For     = (string)(r.Invoice_For    ?? ""),
                    discount        = r.Discount == null ? 0.0 : Convert.ToDouble(r.Discount)
                }).ToList();

                var dues = dueRows.Select(r => new {
                    institutionID   = (int)r.InstitutionID,
                    institutionName = (string)(r.InstitutionName ?? ""),
                    userName        = (string)(r.UserName        ?? ""),
                    phone           = (string)(r.Phone           ?? ""),
                    validation      = (string)(r.Validation      ?? ""),
                    totalDue        = (double)r.TotalDue,
                    dueInvoiceCount = (int)r.DueInvoiceCount
                }).ToList();

                return Ok(new {
                    success = true,
                    data = new {
                        fromDate = from,
                        toDate   = to,
                        monthSummary = new { monthCollected, institutionsPaid, paymentCount },
                        payments,
                        dues,
                        totalCollectedInRange = payments.Sum(p => p.paidAmount),
                        totalDueAll           = dues.Sum(d => d.totalDue)
                    }
                });
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error fetching authority collected payments");
                return StatusCode(500, new { success = false, message = ex.Message });
            }
        }

        // ── POST /api/invoice/sms-recharge ────────────────────────────────────────
        /// <summary>Adds SMS balance and creates a due invoice for the institution.</summary>
        [HttpPost("sms-recharge")]
        public async Task<ActionResult> SmsRecharge([FromBody] SmsRechargeRequest req)
        {
            if (req.InstitutionId <= 0)
                return BadRequest(new { success = false, message = "Invalid institution" });
            if (req.RechargeSms <= 0)
                return BadRequest(new { success = false, message = "SMS quantity must be greater than 0" });
            if (req.PerSmsPrice <= 0)
                return BadRequest(new { success = false, message = "Invalid SMS price" });

            try
            {
                var totalAmount = req.RechargeSms * req.PerSmsPrice;
                var invoiceFor  = $"SMS Recharge ({req.RechargeSms} SMS)";

                var lines = new List<InvoiceLineRequest>
                {
                    new InvoiceLineRequest
                    {
                        Details = invoiceFor,
                        Amount  = totalAmount
                    }
                };

                // ── 1. Create due invoice ──────────────────────────────────────
                var invoiceId = await _billing.CreateInvoiceForInstitutionAsync(
                    req.InstitutionId,
                    invoiceFor,
                    DateTime.Today,
                    DateTime.Today.AddDays(7),
                    discount: 0,
                    lines,
                    isAutoGenerated: false);

                // ── 2. Add SMS balance to SMS table ───────────────────────────
                using var con = _context.CreateConnection();
                var exists = await con.ExecuteScalarAsync<int>(
                    "SELECT COUNT(*) FROM SMS WHERE InstitutionID = @id",
                    new { id = req.InstitutionId });

                if (exists > 0)
                {
                    await con.ExecuteAsync(
                        "UPDATE SMS SET SMS_Balance = ISNULL(SMS_Balance,0) + @qty WHERE InstitutionID = @id",
                        new { qty = req.RechargeSms, id = req.InstitutionId });
                }
                else
                {
                    await con.ExecuteAsync(
                        "INSERT INTO SMS (InstitutionID, SMS_Balance) VALUES (@id, @qty)",
                        new { id = req.InstitutionId, qty = req.RechargeSms });
                }

                _logger.LogInformation("SMS recharge: InstitutionID={id}, SMS={qty}, InvoiceID={inv}",
                    req.InstitutionId, req.RechargeSms, invoiceId);

                return Ok(new { success = true, message = "রিচার্জ সফল হয়েছে", invoiceId });
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error in SmsRecharge for institution {id}", req.InstitutionId);
                return StatusCode(500, new { success = false, message = ex.Message });
            }
        }
    }

    // ── Request models ────────────────────────────────────────────────────────────
    public class InvoiceLineRequest
    {
        public string Details { get; set; } = "";
        public double Amount { get; set; }
    }

    public class CreateInvoiceRequest
    {
        public List<int> InstitutionIds { get; set; } = new();
        public string InvoiceFor { get; set; } = "Monthly Renewal";
        public DateTime? IssuDate { get; set; }
        public DateTime? EndDate { get; set; }
        public double Discount { get; set; }
        public List<InvoiceLineRequest> Lines { get; set; } = new();
    }

    public class UpdatePaymentRequest
    {
        public double AddedAmount { get; set; }
        public double Discount { get; set; }
        public string? CollectedBy { get; set; }
        public string? PaymentMethod { get; set; }
    }

    public class SmsRechargeRequest
    {
        public int InstitutionId { get; set; }
        public int RechargeSms { get; set; }
        public double PerSmsPrice { get; set; }
    }

    public class BulkPaymentItem
    {
        public int InvoiceId { get; set; }
        public double AddedAmount { get; set; }
        public double Discount { get; set; }
    }

    public class BulkPaymentRequest
    {
        public List<BulkPaymentItem> Payments { get; set; } = new();
        public string? CollectedBy { get; set; }
        public string? PaymentMethod { get; set; }
    }
}